apiVersion: v1
kind: Pod
metadata:
  name: resume-pod
  labels:
    app: nginx
    env: prod
spec:
  containers:
    - name: container-read
      image: nginx:1.22.0
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
        requests: 
          memory: "200Mi"
          cpu: "200m"
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

  initContainers:
    - name: init-container
      image: alpine
      command: 
        - wget
        - "-O"
        - "/var/tmp/index.html"
        - https://github.com/ridhampatel24/React-Node-Docker-Project-CICD-JENKINS-EC2-PUBLIC/blob/main/Jenkinsfile?raw=true
      volumeMounts:
        - name: shared-data
          mountPath: /var/tmp
  volumes:
    - name: shared-data
      emptyDir: {}
