apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: nginx-prod
    env: prod
spec:
  nodeName: worker-vm
  containers:
    - image: nginx:1.22.0
      name: test-container
      env:
        - name: OWNER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: owner
      ports:
        - containerPort: 80
          name: nginx-port
          protocol: TCP
          hostPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "500Mi"
        requests:
          cpu: "200m"
          memory: "200Mi"
