apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deploy
  labels:
    app: nginx-prod
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx-demo
      labels:
        env: production
    spec:
      containers:
        - name: write-container
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", 'while true; do echo "Time: `date +%r` POD name: $(cat /var/log/index.html)" > /proc/1/fd/1; sleep 10;done']
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "150Mi"
          volumeMounts:
            - name: shared-data
              mountPath: /var/log
      # volumes:
      #   - name: shared-data
      #     downwardAPI:
      #       items:
      #       - path: index.html
      #         fieldRef:
      #           fieldPath: metadata.name
      volumes:
        - name: shared-data
          downwardAPI:
            items:
            - path: index.html
              resourceFieldRef:
                containerName: write-container
                resource: limits.cpu
            - path: index2.html
              resourceFieldRef:
                containerName: write-container
                resource: requests.memory