apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deploy
  labels:
    app: nginx-prod
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx-demo
      labels:
        env: production
    spec:
      containers:
        - name: write-container
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", 'while true; do echo "Time: `date +%r` POD name: $(cat /var/log/index.html)" > /proc/1/fd/1; sleep 10;done']
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: "0.1"
              memory: "50Mi"
          volumeMounts:
            - name: shared-data
              mountPath: /var/log
      volumes:
        - name: shared-data
          downwardAPI:
            items:
            - path: index.html
              fieldRef:
                fieldPath: metadata.name