apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    app: nginx
    env: prod
spec:
  containers:
    - name: write-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/log/index.html; sleep 10;done"]
      resources:
        limits:
          cpu: "0.1"
          memory: "50Mi"
      volumeMounts:
        - name: my-data
          mountPath: /var/log
        - name: info-data
          mountPath: /var/tmp/info.php
    - name: nginx
      image: nginx:latest
      ports:
        - name: nginx-port 
          containerPort: 80
          protocol: TCP
      env:
        - name: DB_USER
          value: "devops"
      resources:
        limits:
          cpu: "500m"
          memory: "500Mi"
        requests:
          cpu: "0.2"
          memory: "200Mi"
      
      volumeMounts:
        - name: my-data
          mountPath: /usr/share/nginx/html


  volumes:
    - name: my-data
      hostPath:
        path: /home/ubuntu/data
        type: DirectoryOrCreate

    - name: info-data
      hostPath:
        path: /home/ubuntu/info.php
        type: FileOrCreate
