apiVersion: v1
kind: Pod
metadata:
  name: azure-disk-pod
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - mountPath: "/mnt/azure"
          name: azure-volume
  volumes:
    - name: azure-volume
      persistentVolumeClaim:
        claimName: myclaim