apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  nodeName: worker-vm
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - mountPath: "/mnt/azure"
          name: azure-volume
  volumes:
    - name: azure-volume
      persistentVolumeClaim:
        claimName: azure-disk-pvc