apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-prod
    env: prod
  ports:
    - name: http-port
      protocol: TCP
      port: 80  # Service port
      targetPort: 80 # Pod port
  #type: ClusterIP
  # k expose deployment nginx-deploy --port=8090 --target-port=80 --selector=app=nginx-prod --name=nginx-svc
  # In the backend the service is using Endpoints to route the traffic to the pods
  # ClusterIP is the default type
  # ClusterIP: Exposes the service on a cluster-internal IP. Choosing this value makes the service only reachable from within the cluster.
  # <svc-name>.<namespace>.svc.cluster.local  # DNS name of the service in the cluster
  # NodePort: Exposes the service on each Node’s IP at a static port (the NodePort). A ClusterIP service, to which the NodePort service will route, is automatically created.
