apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-prod
    env: prod
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80 
  type: LoadBalancer