apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-prod
    env: prod
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      nodePort: 31000 # Node port
      targetPort: 80 # Pod port
  type: NodePort

  # k expose deployment nginx-deploy --port=8090 --target-port=80 --selector=app=nginx-prod,env=prod --type=NodePort --name=nginx-svc
  