apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    max:
      memory: 1Gi
    min:
      memory: 128Mi
    type: Container

# LimitRange is a policy to constrain resource allocations (to limit the resource consumption) in a namespace.
# LimitRange is only affect new pods, and will not affect existing pods.
