apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-demo-rc
  labels:
    app: nginx
    type: rc-prod

spec:
  #replicas: 1
  selector:
    app: nginx-prod
  template:
    metadata:
      name: nginx-demo
      labels:
        app: nginx-prod
    spec:
     containers:
       - name: nginx
         image: nginx:1.20.0
         ports:
           - containerPort: 80
         resources:
           limits:
             cpu: "0.2"
             memory: "300Mi"
         