apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
  labels:
    app: nginx
    owner: ridham
spec:
  template:
    metadata: 
     name: nginx-pod
     labels:
       app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.20.0
  replicas: 3