apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: nginx
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
  selector:
    matchLabels:
      app: nginx